# Generated by Django 4.0.2 on 2022-03-15 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_pledge'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pledge',
            name='supporter',
        ),
    ]
